Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -22,3 +22,7 @@ jobs:
     - name: Analysing the code with pylint
       run: |
         pylint $(git ls-files '*.py') || pylint-exit $?
+        if [ $? -ne 0 ]; then
+        echo "An error occurred while running pylint." >&2
+        exit 1
+        fi
